name: CI

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - "**.js"
      - "package.json"
      - ".github/workflows/ci.yml"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node: ["12.20.0"]
        exclude:
          # On Windows, run tests with only the LTS environments.
          - os: windows-latest
            node: "12.22.3"
          - os: windows-latest
            node: "16.0.0"
          # On macOS, run tests with only the LTS environments.
          - os: macOS-latest
            node: "12.22.3"
          - os: macOS-latest
            node: "16.0.0"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - run: npm test -- --colors